config/routes.rb
Rails.application.routes.draw do
  root 'status#dashboard'
  post "settingsc/mailalert"
  post 'settingsc/Changepass'
  get 'settingsc/mailalert'
  get 'settingsc/filter'
  post 'settingsc/filter'
  get 'status/GoCDStatus'
  post 'status/GoCDStatus'
  get 'status/GoCDUpdate'
  post 'status/GoCDUpdate'
  get 'status/organization'
  post 'status/verification'
  get 'status/verification'
  get 'status/waiting'
  post 'status/waiting'
  get 'status/dashboard'
  post 'status/boardfilter'
  get 'status/closed'
  post 'status/closed'
  get 'status/stagnated'
  post 'status/stagnated'
  get 'bitbuc/prstatus'
  get 'employee/index'
  get 'employee/show'
  post 'employee/edit'
  get 'employee/edit'
  get 'employee/retrieve'
  post 'employee/index'
  post 'employee/show'=>'employee/modify'
  post 'employee/modify'
  get 'employee/modify'
  post 'employee/delete'
  get 'settingsc/Changepass'
  get 'settingsc/retrieve'
  delete 'employee/show'
  match '/', to: 'status#dashboard', via: [:get, :post]

  get 'status/organization' => 'status/organization_view'
  post 'status/organization' => 'status/organization_edit'
  Rails.application.routes.draw do
    devise_for :devop_users, controllers: {
      sessions: 'devopuser/sessions'
    }
  end

end

app/models/adminlist.rb
class Adminlist < ActiveRecord::Base
  validates :Name, uniqueness: true
end

app/models/allissue.rb
class Allissue < ActiveRecord::Base
end

app/models/changedissue.rb
class Changedissue < ActiveRecord::Base
end

app/models/checkdb.rb
class Checkdb < ActiveRecord::Base


end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
end

app/models/devop_user.rb
class DevopUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
  :recoverable, :rememberable, :trackable, :validatable,:registerable
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  #validates :name, :null => false
  #validates :dfrom,:null => false
  #validates :dto,:null => false
  #validates :reason, :null => false
end

app/models/exclulist.rb
class Exclulist < ActiveRecord::Base
  validates :Name, uniqueness: true
end

app/models/gocddiffer.rb
class PostCollection < ActiveResource::Collection
  def initialize(parsed = {})
    @elements = parsed['jobs']
  end
end
class Gocddiffer < ActiveResource::Base
  self.site="http://192.168.1.104:8153/go/api/agents/3318e5d3-953e-4993-bc6e-f861efcb68e2/job_run_history"
  self.collection_parser = PostCollection
  self.user=Toolsdb.find(2).username
  self.password=Toolsdb.find(2).password
end

app/models/gocdstate.rb
class PostCollection < ActiveResource::Collection
  def initialize(parsed = {})
    @elements = parsed['jobs']
  end
end
class Gocdstate < ActiveResource::Base
  self.site = "http://192.168.1.104:8153/go/api/agents/3318e5d3-953e-4993-bc6e-f861efcb68e2/job_run_history"
  self.collection_parser = PostCollection
  self.user=Toolsdb.find(2).username
  self.password=Toolsdb.find(2).password
end

app/models/issue.rb
class IssueCollection < ActiveResource::Collection
  def initialize(parsed = {})
    @elements = parsed['issues']
  end
end

class Issue < ActiveResource::Base
  self.site = 'http://192.168.1.121/'
  self.user = Toolsdb.find(1).username
  self.password = Toolsdb.find(1).password
  self.collection_parser = IssueCollection

end

app/models/redmine_user.rb
require 'active_resource'
require 'active_support'
class RedmineUser < ActiveRecord::Base
  #belongs_to :user
  #set_primary_key ='name'
  validates :name,    uniqueness: true
end

app/models/time_entries.rb
class TimeCollection < ActiveResource::Collection
  def initialize(parsed = {})
    @elements = parsed['time_entries']
  end
end


class TimeEntries < ActiveResource::Base
  self.site = 'http://192.168.1.121/'
  self.user = Toolsdb.find(1).username
  self.password = Toolsdb.find(1).password
  self.collection_parser = TimeCollection

end

=begin
@shw= TimeEntries.find(:all, :params => { :spent_on => "2017-03-15" })
@di = @shw.to_json
$d = JSON.parse(@di)
=end

app/models/toolsdb.rb
class Toolsdb < ActiveRecord::Base
end

app/models/tracker.rb
class Tracker < ActiveResource::Base
  self.site = 'http://192.168.1.121/'
  self.user = Toolsdb.find(1).username
  self.password = Toolsdb.find(1).password

end

app/models/user.rb
class UserCollection < ActiveResource::Collection
  def initialize(parsed = {})
    @elements = parsed['users']
  end
end

class User < ActiveResource::Base
  #id=1
  self.site='http://192.168.1.121/'
  self.user=Toolsdb.find_by_id(1).username
  self.password=Toolsdb.find_by_id(1).password
  self.collection_parser = UserCollection
end

app/models/verification.rb
class IssueCollection < ActiveResource::Collection
  def initialize(parsed = {})
    @elements = parsed['issues']
  end
end

class Issue < ActiveResource::Base
  self.site = 'http://192.168.1.121/'
  self.user = Toolsdb.find(1).username
  self.password = Toolsdb.find(1).password
  self.collection_parser = IssueCollection

end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController

  def index
    begin
      if params[:delete]
        @mod=Employee.find(params[:id]).destroy
        redirect_to employee_index_path
      elsif params[:edit]
        @@find=Employee.find(params[:id])
        redirect_to employee_edit_path
      end
      @employees=Employee.all
    rescue
      flash[:alert]="There is some problem in accessing database"
    end
  end

  def show
    begin
      case request.method_symbol
      when :post
        if !params[:empLeave].nil? && !params[:leavef].nil? && !params[:leavet].nil? && !params[:message].nil?

          if RedmineUser.where(name:params[:empLeave]).length!=0
            @employee = Employee.create(name:params[:empLeave] ,dfrom:params[:leavef] ,dto:params[:leavet],reason: params[:message])
            redirect_to employee_index_path
          else
            flash[:alert]="You can add only the redmine users"
          end
        end
      when :get
        Employee.where(dfrom:@current_date)
      end
    rescue
      flash[:alert]="There is some problem in accessing database"
    end
  end

  def edit
    begin
      @empl=@@find
    rescue
      flash[:alert]="You can't edit an empty database"
    end
  end

  def modify
    begin
      if params[:update]
        mod=Employee.find(params[:id])
        mod.reason=params[:message]
        mod.dfrom=params[:leavef]
        mod.dto=params[:leavet]
        mod.save
        redirect_to employee_index_path
      end
    rescue
      flash[:alert]="There is some problem in accessing database"
    end
  end

  def retrieve
    @names= RedmineUser.order(:name).where("name like ?","%#{params[:term]}%")
    render json: @names.map(&:name)

  end
end

app/helpers/bitbuc_helper.rb
module BitbucHelper
end

app/helpers/dev_helper.rb
module DevHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/settingsc_helper.rb
module SettingscHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/views/employee/edit.html.erb
<div class="rightdiv">
  <% if flash[:alert] %>
  <div class="alertbox">
    <span class="alerttext"><%= flash[:alert] %></span>
    <%flash[:alert]=nil%>
  </div>
  <% else%>
  <%=form_for("show" ,:url=> employee_modify_path) do |f|%>

  <table class="fix">

    <thead>

      <th colspan = "2"><%=f.label :Leave_Entry %></th>

    </thead>

    <col width="30%">

    <col width="70%">

    <tr>
      <td><%=f.label :Name %></td>
      <td><%=f.text_field :empLeave,name: 'empLeave',:value => @empl.name,:required => true, :class => "textbox",:disabled=>true %></td>
    </tr>

    <tr>
      <td><%=f.label :From %></td>
      <td><%=f.text_field(:leavef,name: 'leavef' ,:value => @empl.dfrom,:required => true, :class => "textbox",id:"leavef") %></td>
    </tr>

    <tr>
      <td><%=f.label :To %></td>
      <td><%= f.text_field(:leavet,name: 'leavet' ,:value => @empl.dto,:required => true, :class => "textbox",id:"leavet") %></td>
    </tr>

    <tr>
      <td><%=f.label :Reason %></td>
      <td><%= f.text_area :message,name:'message', size: "24x6" ,:value => @empl.reason,:required => true, :class => "textbox1"%></td>
      <%=f.hidden_field :id,  name: 'id',:value => @empl.id,:required => true %>
    </tr>

    <tr>
      <td></td><td style="display:inline-block">
        <%=f.submit "Update",:name => 'update', :class=>"button", :style=>"margin-left:0px;"%>&nbsp;
      </tr>

    </table>

    <%end%>
    <%end%>
  </div>

  <style>

  tr,td {

    border:0

  }

  table {

    width: 50%;
    margin-left: 300px;
    margin-top: 100px;

  }

  </style>

</div>
<script type="text/javascript">
$(document).ready(function(){
  $('#leavef').datepicker({
    format: 'dd M yyyy',
    autoclose: true,
    minDate: 0,
    onSelect: function(selected) {
      console.log(selected)
      $("#leavet").datepicker("option","minDate", selected);
    }
  });

  $('#leavet').datepicker({
    format: 'dd M yyyy',
    autoclose: true,
    onSelect: function(selected) {
      console.log(selected)
      $("#leavef").datepicker("option","maxDate", selected);
    }
  });

})

</script>

app/views/employee/index.html.erb
<div class="rightdiv">
  <% if flash[:alert] %>
  <div class="alertbox">
    <span class="alerttext"><%= flash[:alert] %></span>
    <%flash[:alert]=nil%>
  </div>
  <% else%>

  <div style="float:right; padding:10px;" >

    <%= button_to 'New', employee_show_path, :class=>"button" %>

  </div>

  <%= form_for('index') do |f|%>
  <%if(@employees.length==0)%>
  <h2 style="margin:10px;padding:10px">No Leave Entries</h2>
  <%else%>
  <table>

    <thead>

      <th>Serial No</th>
      <th>Employee Name</th>
      <th>From</th>
      <th>To</th>
      <th>Reason</th>

    </thead>

    <%@employees.each do |emp|%>

    <tr>

      <td>
        <%= radio_button_tag :id,"#{emp.id}" ,checked="checked" %>
        <%=emp.id%></td>
        <td><%=emp.name%></td>
        <td><%=emp.dfrom%></td>
        <td><%=emp.dto%></td>
        <td><%=emp.reason%></td>

      </tr>

      <%end%>

      <div style="margin-left:875px;padding:10px">
        <%= f.button 'Edit',:url => employee_edit_path,:class=>"button",:name=>"edit" %>
        <%= f.button 'Delete',:url => employee_index_path, :class=>"button",:name=>"delete"%></td>
      </div>

    </table>
    <%end%>
    <%end%>
    <%end%>

  </div>

app/views/employee/show.html.erb
<div class="rightdiv">
  <%=form_for("show") do |f|%>
  <table class="fix">

    <thead>

      <th colspan = "2"><%=f.label :Leave_Entry %></th>

    </thead>

    <col width="30%">

    <col width="70%">

    <tr>
      <td><%=f.label :Name %></td>
      <td><%=f.text_field :empLeave,  name: 'empLeave' ,data: {autocomplete_source: employee_retrieve_path,method: :get} , :required => true, :class => "textbox" %></td>
    </tr>

    <tr>
      <td><%=f.label :From %></td>
      <td><%= f.text_field(:leavef,name: 'leavef' ,:required => true, :class => "textbox",id:"leavef") %></td>
    </tr>

    <tr>
      <td><%=f.label :To %></td>
      <td><%= f.text_field(:leavet,name: 'leavet' ,:required => true, :class => "textbox",id:"leavet") %></td>
    </tr>

    <tr>
      <td><%=f.label :Reason %></td>
      <td><%= f.text_area :message,name:'message', size: "24x6" ,:required => true, :class => "textbox1"%></td>
    </tr>

    <tr>
      <% if flash[:alert] %>
      <td colspan="2">
        <span style="color:red;margin-left:135px"><%= flash[:alert] %></span>
        <%flash[:alert]=nil%></td>
        <%end%>
      </tr>
      <tr>
        <td></td><td style="display:inline-block"><%=f.submit "Submit",:name => 'save', :class=>"button", :style=>"margin-left:0px;"%>&nbsp;
          <button type="reset" value="Reset" class="button">Reset</button>
        </td>
      </tr>

    </table>



    <%end%>
  </div>
  <style>
  tr,td {
    border:0
  }
  table {
    width: 50%;
    margin-left: 300px;
    margin-top: 100px;
  }
  </style>

</div>
<script type="text/javascript">
$(document).ready(function(){
  $('#leavef').datepicker({
    format: 'dd M yyyy',
    autoclose: true,
    minDate: 0,
    onSelect: function(selected) {
      console.log(selected)
      $("#leavet").datepicker("option","minDate", selected);
    }
  });

  $('#leavet').datepicker({
    format: 'dd M yyyy',
    autoclose: true,
    onSelect: function(selected) {
      console.log(selected)
      $("#leavef").datepicker("option","maxDate", selected);
    }
  });

})

</script>