config/routes.rb
Rails.application.routes.draw do
  root 'status#dashboard'
  post "settingsc/mailalert"
  post 'settingsc/Changepass'
  get 'settingsc/mailalert'
  get 'settingsc/filter'
  post 'settingsc/filter'
  get 'status/GoCDStatus'
  post 'status/GoCDStatus'
  get 'status/GoCDUpdate'
  post 'status/GoCDUpdate'
  get 'status/organization'
  post 'status/verification'
  get 'status/verification'
  get 'status/waiting'
  post 'status/waiting'
  get 'status/dashboard'
  post 'status/boardfilter'
  get 'status/closed'
  post 'status/closed'
  get 'status/stagnated'
  post 'status/stagnated'
  get 'bitbuc/prstatus'
  get 'employee/index'
  get 'employee/show'
  post 'employee/edit'
  get 'employee/edit'
  get 'employee/retrieve'
  post 'employee/index'
  post 'employee/show'=>'employee/modify'
  post 'employee/modify'
  get 'employee/modify'
  post 'employee/delete'
  get 'settingsc/Changepass'
  get 'settingsc/retrieve'
  delete 'employee/show'
  match '/', to: 'status#dashboard', via: [:get, :post]

  get 'status/organization' => 'status/organization_view'
  post 'status/organization' => 'status/organization_edit'
  Rails.application.routes.draw do
    devise_for :devop_users, controllers: {
      sessions: 'devopuser/sessions'
    }
  end

end

app/controllers/settingsc_controller.rb
class SettingscController < ApplicationController
  def filter
    begin
      case request.method_symbol
      when :get
      when :post
        if params[:stagnated_days]
          dummy=Toolsdb.find(4)
          dummy.password=params[:stagnated_days]
          dummy.save
        elsif params[:logged_hours]
          dummy=Toolsdb.find(5)
          dummy.password=params[:logt_hours]
          dummy.save
        end
      end
    rescue
      flash[:alert]="There is some problem in accessing database"
    end
  end

  def Changepass
    begin
      case request.method_symbol
      when :get
      when :post
        if params[:redmine]
          user=Toolsdb.find(1).username
          pwd=Toolsdb.find(1).password
          if (pwd==params[:Changepass]['cupass'] && params[:Changepass]['npass']==params[:Changepass]['cnpass'])
            dummy=Toolsdb.find(id)
            dummy.username=params[:Changepass]['user']
            dummy.password=params[:Changepass]['cnpass']
            dummy.save
            if !dummy.save!
              flash[:alert]="your password or username is incorrect"
            end
          else
            flash[:alert] = "Your Password or Username is Incorrect"

          end

        elsif params[:cdgo]
          user=Toolsdb.find(2).username
          pwd=Toolsdb.find(2).password
          if (pwd==params[:Changepass]['cupass'] && params[:Changepass]['npass']==params[:Changepass]['cnpass'])
            dummy=Toolsdb.find(2)
            dummy.username=params[:Changepass]['user']
            dummy.password=params[:Changepass]['cnpass']
            dummy.save
            if !dummy.save!
              flash[:alert1]="your password or username is incorrect"
            end
          else
            flash[:alert1] = "Your Password or Username is Incorrect"
            redirect_to settingsc_Changepass_path
          end

        elsif params[:bb]
          user=Toolsdb.find(3).username
          pwd=Toolsdb.find(3).password
          if (pwd==params[:Changepass]['cupass'] && params[:Changepass]['npass']==params[:Changepass]['cnpass'])
            dummy=Toolsdb.find(2)
            dummy.username=params[:Changepass]['user']
            dummy.password=params[:Changepass]['cnpass']
            dummy.save
            if !dummy.save!
              flash[:alert2]="your password or username is incorrect"
            end
          else
            flash[:alert2] = "Your Password or Username is Incorrect"
            redirect_to settingsc_Changepass_path
          end
        end
      end
    rescue
      flash[:alert]="There is some problem in accessing database"
    end
  end


  def mailalert
    case request.method_symbol
    when :get
    when :post
      if params[:adminadd]
        begin
          @add = RedmineUser.where(name:params[:admintext])
          @db = Adminlist.create(Name:@add[0].name,emailid:@add[0].mailid)
          @db.save
        rescue
          flash[:adminad]="You can add only the redmine users"
        end
      elsif params[:admindel]
        begin
          @del=Adminlist.where(Name:params[:admintext])
          @del[0].delete
        rescue
          flash[:adminde]="You can delete only the already added admin users"
        end
      elsif params[:excluadd]
        begin
          @add=RedmineUser.where(name:params[:exclutext])
          @db= Exclulist.create(Name:@add[0].name,emailid:@add[0].mailid)
          @db.save
        rescue

          flash[:userad]="You can add only the redmine users"
        end
      elsif params[:excludel]
        begin
          @del=Exclulist.where(Name:params[:exclutext])
          @del[0].delete
        rescue
          flash[:userde]="You can delete only the already added admin users"
        end
      end
    end
    @admin=Adminlist.all
    @exclu=Exclulist.all
  end

  def retrieve
    @names= RedmineUser.order(:name).where("name like ?","%#{params[:term]}%")
    render json: @names.map(&:name)

  end
end

app/helpers/settingsc_helper.rb
module SettingscHelper
end

app/views/settingsc/Changepass.html.erb
<div class="rightdiv">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <% if flash[:alert] %>
  <div class="alertbox">
    <span class="alerttext"><%= flash[:alert] %></span>
    <%flash[:alert]=nil%>
  </div>
  <% else%>
  <ul id="tab" class="nav nav-tabs" style="padding:30px 0px 0px 30px">
    <li id="tred" class="active"><a data-toggle="tab"  href="#red">Redmine</a></li>
    <li id="tcdgo"><a data-toggle="tab" href="#go">GoCD</a></li>
    <li id="tbb"><a data-toggle="tab" href="#bit">BitBucket</a></li>
  </ul>


  <div class="tab-content authform">
    <div id="red" class="tab-pane fade in active">
      <%= form_for('Changepass') do |f|%>
      <% if flash[:alert] %>

      <div style="margin-left:100px;color:red"><%= flash[:alert] %></div>
      <% end %>
      <table >
        <tr>
          <td><%= f.label :User_Name %></td>
          <td><%= f.text_field :user ,:class=>"textbox",:required => true%></td>
        </tr>
        <tr>
          <td><%= f.label :Current_Password %></td>
          <td><%= f.password_field :cupass ,:class=>"textbox",:required => true%></td>
        </tr>
        <tr>
          <td><%= f.label :New_Password %></td>
          <td><%= f.password_field :npass ,:class=>"textbox",:required => true%></td>
        </tr>
        <tr>
          <td><%= f.label :Confirm_Password %></td>
          <td><%= f.password_field :cnpass ,:class=>"textbox",:required => true%></td>
        </tr>
        <tr>
          <td></td>
          <td><%= f.submit "Submit" ,:name=>"redmine",:class=>"button",:style=>"margin-left:0px" %>
            <button type="reset" value="Reset" style="margin-left:20px" class="button">Reset</button>
          </td>
        </tr>
      </table>
      <%end%>
    </div>
    <div id="go" class="tab-pane fade">
      <%= form_for('Changepass') do |f|%>
      <% if flash[:alert1] %>
      <script>
      $("#tred").removeClass("active");
      $("#tcdgo").addClass("active");
      $("#red").removeClass("in active");
      $("#go").addClass("in active");
      </script>
      <div style="margin-left:100px;color:red"><%= flash[:alert1] %></div>
      <% end %>
      <table >
        <tr>
          <td><%= f.label :User_Name %></td>
          <td><%= f.text_field :user ,:class=>"textbox",:required => true%></td>
        </tr>
        <tr>
          <td><%= f.label :Current_Password %></td>
          <td><%= f.password_field :cupass ,:class=>"textbox",:required => true%></td>
        </tr>
        <tr>
          <td><%= f.label :New_Password %></td>
          <td><%= f.password_field :npass ,:class=>"textbox",:required => true%></td>
        </tr>
        <tr>
          <td><%= f.label :Confirm_Password %></td>
          <td><%= f.password_field :cnpass ,:class=>"textbox",:required => true%></td>
        </tr>
        <tr>
          <td></td>
          <td><%= f.submit "Submit",:name=>"cdgo",:class=>"button",:style=>"margin-left:0px"%>
            <button type="reset" value="Reset" style="margin-left:20px" class="button">Reset</button>
          </td>
        </tr>
      </table>
      <%end%>
    </div>



    <div id="bit" class="tab-pane fade">
      <%= form_for('Changepass') do |f|%>
      <div id="bd" style="margin-left:100px;color:red;"><%= flash[:alert2] %></div>
      <% if flash[:alert2] %>
      <script>
      $("#tred").removeClass("active");
      $("#tbb").addClass("active");
      $("#red").removeClass("in active");
      $("#bit").addClass("in active");
      </script>
      <% end %>
      <table >
        <tr>
          <td><%= f.label :User_Name %></td>
          <td><%= f.text_field :user ,:class=>"textbox",:required => true%></td>
        </tr>
        <tr>
          <td><%= f.label :Current_Password %></td>
          <td><%= f.password_field :cupass ,:class=>"textbox",:required => true%></td>
        </tr>
        <tr>
          <td><%= f.label :New_Password %></td>
          <td><%= f.password_field :npass ,:class=>"textbox",:required => true%></td>
        </tr>
        <tr>
          <td><%= f.label :Confirm_Password %></td>
          <td><%= f.password_field :cnpass ,:class=>"textbox",:required => true%></td>
        </tr>
        <tr>
          <td></td>
          <td><%= f.submit "Submit",:name=>"bb",:class=>"button",:style=>"margin-left:0px"%>
            <button type="reset" value="Reset" style="margin-left:20px" class="button">Reset</button>
          </td>
        </tr>
      </table>
      <%end%>
    </div>

  </div>
  <%end%>
</div>
<style media="screen">
tr,td,table {
  border:0
  }  </style>

app/views/settingsc/filter.html.erb
<div class="rightdiv">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <% if flash[:alert] %>
  <div class="alertbox">
    <span class="alerttext"><%= flash[:alert] %></span>
    <%flash[:alert]=nil%>
  </div>
  <% else%>
  <ul id="tab" class="nav nav-tabs" style="padding:30px 0px 0px 30px">
    <li id="tred" class="active"><a data-toggle="tab"  href="#stagf">Stagnated Days</a></li>
    <li id="tcdgo"><a data-toggle="tab" href="#mailf">Log Hours</a></li>
  </ul>
  

  <div class="tab-content authform">
    <div id="stagf" class="tab-pane fade in active">
      <%= form_for('stagnated_days') do |f|%>
      <%= f.label :Stagnated__Days, value: "No. of days",:style=>"font-size:20px;color:#384d8c"%>
      <%= f.number_field :number,name: 'stagnated_days',:class=>"textbox",:required => true%>
      <%= f.submit :stagnated_days,name: "stagnated_days",id:"button", value: "Add",:class=>"button", :style => "margin:15px 0 0 280px"%>
      <div id="hidden_input"></div>
      <% end%>
    </div>
    <div id="mailf" class="tab-pane fade">
      <%= form_for('log_hours') do |f|%>
      <%= f.label :loghour, value: "Log Hours",:style=>"font-size:20px;color:#384d8c;margin-left:65px"%>
      <%= f.number_field :number,name: 'logt_hours',:class=>"textbox",:required => true%>
      <%= f.submit :log_hours,name: "logged_hours",id:"button1", value: "Add",:class=>"button", :style => "margin:15px 0 0 280px"%>
      <div id="hidden_input"></div>
      <% end%>
    </div>
  </div>
  <%end%>
</div>
<script>
$(document).ready(function(){
  var hiddenInput1;
  var hiddenInput;

  $('#button').click(function(){
    hiddenInput1 = $('#stagnated_days_number').val();
    //alert(hiddenInput1);
    hiddenInput = $('<input/>',{type:'hidden',id:this.value, name:'stagnated_days', value:hiddenInput1});
    $("#hidden_input").append(hiddenInput);
  });
  $('#button1').click(function(){
    hiddenInput1 = $('#log_hours_number').val();
    //alert(hiddenInput1);
    hiddenInput = $('<input/>',{type:'hidden',id:this.value, name:'log_hours', value:hiddenInput1});
    $("#hidden_input").append(hiddenInput);
  });
});
</script>

app/views/settingsc/mailalert.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<div class="rightdiv">
  <div class="col-sm-6">
    <h3 style="text-align:center;color:#384d8c ">Admin List</h3>
    <%= form_for('mailalert') do |f|%>
    <%= f.label :Name,:style=>"font-size:20px;color:#384d8c"%>
    <%= f.text_field :adminlist,name: 'admintext',data: {autocomplete_source: settingsc_retrieve_path,method: :get},:class=>"textbox",:required => true%>
    <%= f.submit :adminadd,name: "adminadd",value: "Add",:class=>"button"%>
    <%= f.submit :admindel,name: "admindel",value: "Delete",:class=>"button"%>
    <% end%>
    <% if flash[:adminad] %>
    <script>alert("You can add only the redmine users");</script>
    <%flash[:adminad]=nil%>
    <% elsif flash[:adminde] %>
    <script>alert("You can delete only the already added admin users");</script>
    <%flash[:adminde]=nil%>
    <% elsif flash[:userad] %>
    <script>alert("You can add only the redmine users");</script>
    <%flash[:userad]=nil%>
    <% elsif flash[:userde] %>
    <script>alert("You can delete only the already added admin users");</script>
    <%flash[:userde]=nil%>
    <%end%>
    <% if @admin.length==0%>
    <h3>No Admins added</h3>
    <% else %>
    <div class="scrol">
      <table style="margin-top:0px">
        <% @admin.each do |item|%>
        <tr>
          <td ><%= item["Name"]%></td>
        </tr>
        <% end%>
      </table>
    </div>
    <%end%>

  </div>
  <div class="col-sm-6">
    <h3 style="text-align:center;color:#384d8c ">Mail Exclusion List</h3>
    <%= form_for('mailalert') do |f|%>
    <%= f.label :Name,:style=>"font-size:20px;color:#384d8c"%>
    <%= f.text_field :excluList,name: 'exclutext',data: {autocomplete_source: settingsc_retrieve_path,method: :get},:class=>"textbox",:required => true%>
    <%= f.submit :excluadd,name: "excluadd",value: "Add",:class=>"button"%>
    <%= f.submit :excludel,name: "excludel",value: "Delete",:class=>"button"%>
    <% end%>
    <% if @exclu.length==0%>
    <h3>No Users are Excluded</h3>
    <% else %>
    <div class="scrol">
      <table style="margin-top:0px">
        <% @exclu.each do |item|%>
        <tr>
          <td ><%= item["Name"]%></td>
        </tr>
        <% end%>
      </table>
    </div>
    <%end%>
  </div>

</div>
<style media="screen">
td{
  font-size: 20px;
}
table ,tr, td{
  border:0;
}

</style>