config/routes.rb
Rails.application.routes.draw do
  root 'status#dashboard'
  post "settingsc/mailalert"
  post 'settingsc/Changepass'
  get 'settingsc/mailalert'
  get 'settingsc/filter'
  post 'settingsc/filter'
  get 'status/GoCDStatus'
  post 'status/GoCDStatus'
  get 'status/GoCDUpdate'
  post 'status/GoCDUpdate'
  get 'status/organization'
  post 'status/verification'
  get 'status/verification'
  get 'status/waiting'
  post 'status/waiting'
  get 'status/dashboard'
  post 'status/boardfilter'
  get 'status/closed'
  post 'status/closed'
  get 'status/stagnated'
  post 'status/stagnated'
  get 'bitbuc/prstatus'
  get 'employee/index'
  get 'employee/show'
  post 'employee/edit'
  get 'employee/edit'
  get 'employee/retrieve'
  post 'employee/index'
  post 'employee/show'=>'employee/modify'
  post 'employee/modify'
  get 'employee/modify'
  post 'employee/delete'
  get 'settingsc/Changepass'
  get 'settingsc/retrieve'
  delete 'employee/show'
  match '/', to: 'status#dashboard', via: [:get, :post]

  get 'status/organization' => 'status/organization_view'
  post 'status/organization' => 'status/organization_edit'
  Rails.application.routes.draw do
    devise_for :devop_users, controllers: {
      sessions: 'devopuser/sessions'
    }
  end

end

app/models/adminlist.rb
class Adminlist < ActiveRecord::Base
  validates :Name, uniqueness: true
end

app/models/allissue.rb
class Allissue < ActiveRecord::Base
end

app/models/changedissue.rb
class Changedissue < ActiveRecord::Base
end

app/models/checkdb.rb
class Checkdb < ActiveRecord::Base


end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
end

app/models/devop_user.rb
class DevopUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
  :recoverable, :rememberable, :trackable, :validatable,:registerable
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  #validates :name, :null => false
  #validates :dfrom,:null => false
  #validates :dto,:null => false
  #validates :reason, :null => false
end

app/models/exclulist.rb
class Exclulist < ActiveRecord::Base
  validates :Name, uniqueness: true
end

app/models/gocddiffer.rb
class PostCollection < ActiveResource::Collection
  def initialize(parsed = {})
    @elements = parsed['jobs']
  end
end
class Gocddiffer < ActiveResource::Base
  self.site="http://192.168.1.104:8153/go/api/agents/3318e5d3-953e-4993-bc6e-f861efcb68e2/job_run_history"
  self.collection_parser = PostCollection
  self.user=Toolsdb.find(2).username
  self.password=Toolsdb.find(2).password
end

app/models/gocdstate.rb
class PostCollection < ActiveResource::Collection
  def initialize(parsed = {})
    @elements = parsed['jobs']
  end
end
class Gocdstate < ActiveResource::Base
  self.site = "http://192.168.1.104:8153/go/api/agents/3318e5d3-953e-4993-bc6e-f861efcb68e2/job_run_history"
  self.collection_parser = PostCollection
  self.user=Toolsdb.find(2).username
  self.password=Toolsdb.find(2).password
end

app/models/issue.rb
class IssueCollection < ActiveResource::Collection
  def initialize(parsed = {})
    @elements = parsed['issues']
  end
end

class Issue < ActiveResource::Base
  self.site = 'http://192.168.1.121/'
  self.user = Toolsdb.find(1).username
  self.password = Toolsdb.find(1).password
  self.collection_parser = IssueCollection

end

app/models/redmine_user.rb
require 'active_resource'
require 'active_support'
class RedmineUser < ActiveRecord::Base
  #belongs_to :user
  #set_primary_key ='name'
  validates :name,    uniqueness: true
end

app/models/time_entries.rb
class TimeCollection < ActiveResource::Collection
  def initialize(parsed = {})
    @elements = parsed['time_entries']
  end
end


class TimeEntries < ActiveResource::Base
  self.site = 'http://192.168.1.121/'
  self.user = Toolsdb.find(1).username
  self.password = Toolsdb.find(1).password
  self.collection_parser = TimeCollection

end

=begin
@shw= TimeEntries.find(:all, :params => { :spent_on => "2017-03-15" })
@di = @shw.to_json
$d = JSON.parse(@di)
=end

app/models/toolsdb.rb
class Toolsdb < ActiveRecord::Base
end

app/models/tracker.rb
class Tracker < ActiveResource::Base
  self.site = 'http://192.168.1.121/'
  self.user = Toolsdb.find(1).username
  self.password = Toolsdb.find(1).password

end

app/models/user.rb
class UserCollection < ActiveResource::Collection
  def initialize(parsed = {})
    @elements = parsed['users']
  end
end

class User < ActiveResource::Base
  #id=1
  self.site='http://192.168.1.121/'
  self.user=Toolsdb.find_by_id(1).username
  self.password=Toolsdb.find_by_id(1).password
  self.collection_parser = UserCollection
end

app/models/verification.rb
class IssueCollection < ActiveResource::Collection
  def initialize(parsed = {})
    @elements = parsed['issues']
  end
end

class Issue < ActiveResource::Base
  self.site = 'http://192.168.1.121/'
  self.user = Toolsdb.find(1).username
  self.password = Toolsdb.find(1).password
  self.collection_parser = IssueCollection

end

app/helpers/bitbuc_helper.rb
module BitbucHelper
end

app/helpers/dev_helper.rb
module DevHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devops PMS</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>


  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>

  <div class="menubar">
    <div id="userpanel">
      <%= link_to "Login",new_devop_user_session_path,class: "#{'hidden' if devop_user_signed_in?}",disabled: true,:style=>"color:white" %>
      <%= link_to "Logout",destroy_devop_user_session_path , method: :delete,class: "#{'hidden' if !devop_user_signed_in?}",disabled: true,:style=>"color:white" %>
    </div>
    <h4 class="heading">DevOps PMS</h4>
  </div>
  <div class="ro">
    <div id="divMenu">
      <ul>
        <li><%= link_to "Home",root_path %>
        </li>
        <li><a href="#">Red Mine</a>
          <ul>
            <li><%= link_to "Waiting Issues" ,status_waiting_path %></li>
            <li><%= link_to "Verification Issues" ,status_verification_path  %></li>
            <li><%= link_to "Closed Issues" ,status_closed_path %></li>
            <li><%= link_to "Stagnated Issues" ,status_stagnated_path %></li>
          </ul></li>
          <li><a href="#">GoCD</a>
            <ul>
              <li ><%= link_to "Build status" ,status_GoCDStatus_path %><li>
                <li ><%=link_to "Build Update" ,status_GoCDUpdate_path %><li>
                </ul></li>
                <li><a href="#">Bit Bucket</a>
                  <ul>
                    <li><%= link_to "PR Request", bitbuc_prstatus_path%></li>
                  </ul></li>
                  <li>
                    <%= link_to "Settings","#",class: "#{'hidden' if !devop_user_signed_in?}",disabled: true,:style=>"color:#384d8c;display:visible" %>
                    <ul>
                      <li><%= link_to "Organization Leave", status_organization_path%></li>
                      <li><%= link_to "Employee Leave", employee_index_path %></li>
                      <li><%= link_to "Change Password", settingsc_Changepass_path %></li>
                      <li><%= link_to "Mail Alert", settingsc_mailalert_path %></li>
                      <li><%= link_to "Filter Stagnated", settingsc_filter_path %></li>
                    </ul>
                  </li>
                </ul>
              </div>

              <%= yield %>
            </div>
            <footer class="footer">
              <div>
                <p>copyright<i class="fa fa-copyright"></i>appranix.com</p>
              </div>
            </footer>
          </body>
          </html>

app/views/layouts/first.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devops PMS</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script type="text/javascript" src="script.js"></script>

  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


</head>

<body>

  <div class="menubar">
    <h4 class="heading">DevOps PMS</h4>
  </div>
  <div class="ro">

    <%= yield %>
  </div>
  <footer class="footerlogin">
    <div>
      <p>copyright<i class="fa fa-copyright"></i>appranix.com</p>
    </div>
  </footer>

</body>
</html>

app/views/sendmail/mailing.html.erb
<head>
<style media="screen">
table ,td,tr{
  border:1px solid black;
  border-collapse: collapse;
}
</style>
</head>
<body>
  <p style="text-align:centre"><b>Redmine Users Log Time - <%=Date.today.to_s%></b></p>
  <table>
    <tr>
      <thead style="font-weight:bold">
        <td>Name</td>
        <td>Total Time Spent</td>
        <td>Issues Id</td>
        <td>Issues Time Spent</td>
      </thead>
    </tr>
    <%  @users.each do |ss|%>
    <%  @timeentries=TimeEntries.find(:all, :params => { :spent_on => @current_date, :user_id =>ss['id']})%>
    <%@timeentriesjson =  @timeentries.to_json%>
    <%@timeentriesjsons = JSON.parse(@timeentriesjson)%>
    <%@lent=@timeentriesjsons.length%>
    <%i=0%>
    <%if @lent!=0%>
    <%@total_time_spent=0%>
    <%@logflag=0%>
    <%@timeentriesjsons.each do%>
    <%@total_time_spent+=@timeentriesjsons[i]['hours']%>
    <% i+=1 %>
    <%end%>
    <%if @total_time_spent < Toolsdb.find(5).password.to_f%>
    <%@logflag=1%>
    <%end%>
    <%i=0%>
    <%if @logflag==1%>
    <tr>

      <td rowspan="<%=@lent%>"><b><%=ss['firstname']+" "+ss['lastname']%></b></td>
      <td rowspan="<%=@lent%>"><b><%=@total_time_spent%></b></td>
      <%@timeentriesjsons.each do%>
      <td><b><a href="http://192.168.1.121/issues/<%=@timeentriesjsons[i]['issue']['id']%>"><%="#"+@timeentriesjsons[i]['issue']['id'].to_s%></a></b></td>
      <td><b><%=@timeentriesjsons[i]['hours'].to_s%></b></td>
    </tr>
    <% i+=1 %>
    <%end%>
    <%else%>
    <tr>

      <td rowspan="<%=@lent%>"><%=ss['firstname']+" "+ss['lastname']%></td>
      <td rowspan="<%=@lent%>"><%=@total_time_spent%></td>
      <%@timeentriesjsons.each do%>
      <td><a href="http://192.168.1.121/issues/<%=@timeentriesjsons[i]['issue']['id']%>"><%="#"+@timeentriesjsons[i]['issue']['id'].to_s%></a></td>
      <td><%=@timeentriesjsons[i]['hours'].to_s%></td>
    </tr>
    <% i+=1 %>
    <%end%>
    <%end%>
    <%end%>
    <%end%>


    <%@unloggedusers.each do |unlogged|%>
    <%if unlogged[2]!=nil && unlogged[3]!=nil%>
    <tr>
      <td style="color:#ff0000"><%=unlogged[2]+" "+unlogged[3]%></td>
      <td style="color:#ff0000">0</td>
      <td style="color:#ff0000">0</td>
      <td style="color:#ff0000">0</td>
    </tr>
    <%end%>
    <%end%>


    <%@holidayUsers.each do |husers|%>
    <%if husers[0]!=nil && husers[1]!=nil%>
    <tr>
      <td><%=husers[0]+" "+husers[1]%></td>
      <td>On Leave</td>
      <td></td>
      <td></td>

    </tr>
    <%end%>
    <%end%>


  </table>
</body>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: ''), calendar.url_for_previous_view ,:class=>"fa fa-angle-double-left arrow"%>
    <span class="calendar-title"><%= t('date.abbr_month_names')[start_date.month] %> <%= start_date.year%></span>
    <%= link_to t('simple_calendar.next', default: ''), calendar.url_for_next_view ,:class=>"fa fa-angle-double-right arrow"%>
  </div>

  <table class="table table-striped"  style="width:98%">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/unlogged/sendUnloggedmail.html.erb
<html>
<head>
<style>
p {
  padding-left: 30px;
}
</style>
</head>
<body>
  Hi <%= @firstname+" "+@lastname %>,
  <p>You have not logged in Redmine on <%= Date.today.to_s%></p>
  Regards,<br>
  Appranix Team
</body>
</html>